version: '3'
services:
  server:
    build: ./nginx
    ports: 
      - "80:80"
    volumes:
      - ./flashcards:/var/www/
      - ./flashcards-front:/var/www-front/
      - ./logs:/var/log/nginx/
    depends_on: 
      - php

  php:
    build: 
        context: ./flashcards
        dockerfile: Dockerfile.prod
    ports:
      - "9003:9003"
    volumes:
      - ./flashcards:/var/www/
    extra_hosts:
      - host.docker.internal:host-gateway

  frontend:
    build: ./flashcards-front
    volumes:
      - ./flashcards-front:/home/node/app

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8008:80
    environment:
      PMA_HOST: host.docker.internal
      PMA_USER: flashcards
      PMA_PASSWORD: admin
      PMA_DATABASE: flashcards_db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wagtail: 
    build: ./wagtail
    ports: 
      - "8080:8000"
    volumes:
      - ./wagtail:/app
    command: gunicorn aktulibre.wsgi
    depends_on:
      db: 
        condition: service_started

volumes:
  flashcards:
  flashcards-front:
