version: '3'
services:
  server:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./flashcards:/var/www/
      - ./flashcards-front:/var/www-front/
      - ./logs:/var/log/nginx/
      - ./wagtail:/var/www-wagtail/
    depends_on: 
      - php

  php:
    build: 
        context: ./flashcards
        dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "9003:9003"
    volumes:
      - ./flashcards:/var/www/
    extra_hosts:
      - host.docker.internal:host-gateway

  frontend:
    build: ./flashcards-front
    restart: "no"
    command: /bin/sh -c "npm install && npm run build"
    volumes:
      - ./flashcards-front:/home/node/app
      - /home/node/app/node_modules

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: host.docker.internal
      PMA_USER: flashcards
      PMA_PASSWORD: admin
      PMA_DATABASE: flashcards_db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wagtail: 
    build: ./wagtail
    restart: always
    ports: 
      - "8080:8000"
    volumes:
      - ./wagtail:/app
    command: gunicorn aktulibre.wsgi
    
  redis:
    image: redis

volumes:
  flashcards:
  flashcards-front:
  wagtail:
