version: '3'
services:
  server:
    build: 
      context: ./flashcards
      dockerfile: Dockerfile        
    ports: 
      - "8000:8000"
    volumes:
      - ./flashcards:/var/www
    depends_on:
      db:
        condition: service_started

  # frontend:
  #   build: ./flashcards-front
  #   ports:
  #     - "4200:8000"
  #   volumes:
  #     - ./flashcards-front:/home/node/app

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: flashcards_db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8008:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin 

volumes:
  flashcards:
  flashcards-front:
