version: '3'
services:
  server:
    build: ./nginx
    ports: 
      - "8000:80"
    volumes:
      - ./flashcards:/var/www/
      - ./logs:/var/log/nginx/
    depends_on:
      - php

  php:
    build: 
        context: ./flashcards
        dockerfile: Dockerfile.prod
    ports:
      - "9003:9003"
    volumes:
      - ./flashcards:/var/www/
    extra_hosts:
      - host.docker.internal:host-gateway

  # frontend:
  #   build: ./flashcards-front
  #   ports:
  #     - "4200:8000"
  #   volumes:
  #     - ./flashcards-front:/home/node/app

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8008:80
    environment:
      PMA_HOST: host.docker.internal
      PMA_USER: root
      PMA_PASSWORD: admin 
    extra_hosts:
      - "host.docker.internal:host-gateway"



volumes:
  flashcards:
  flashcards-front:

