FROM php:8.2-cli-alpine

RUN docker-php-ext-install \
    bcmath \
    pdo_mysql

RUN apk add --no-cache \
    npm \
    linux-headers

RUN apk add --no-cache $PHPIZE_DEPS 

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . /var/www
WORKDIR /var/www

RUN composer upgrade

EXPOSE 8000

CMD [ "php", "artisan", "serve", "--host", "0.0.0.0" ]
